<template>
  <div>
    <h4 v-if="log" @click="signout">logout</h4>
    <h1>Welcome to ToDo app</h1>
    <Content v-if="log"></Content>
    <div v-if="statTok">
    <h2 @click="changestat">{{statuser}}</h2>
    <div class="card-deck">
    <Register v-if="statreg" class="slide-in-elliptic-top-fwd"></Register> <Login v-if="statlog" class="slide-in-elliptic-top-fwd"></Login>
    </div> 
    <router-view/>
    </div>   
  </div>
</template>

<script>
    import Register from './Register'
    import Login from './Login'
    import Content from './Content'

    export default {
        name: 'Home',
        components: {
            'Register': Register,
            'Login' : Login,
            'Content' : Content
        },
        data(){
          return{
            statuser: "Click me if you want to Register",
            statreg: false,
            statlog: true,
            token: window.localStorage["todo-token"],
            statTok: true,
            log: false
          }
        },
        created () {
            if (this.token) {
              this.statTok=false
              this.log=true
            }else{
              this.statTok=true
              this.log=false
            }          
        },
        methods:{
          changestat(){
            if(this.statuser == "Click me if you want to Register"){
              this.statuser = "Click me if you want to Login"
              this.statreg = true
              this.statlog = false
            }else{
              this.statuser = "Click me if you want to Register"
              this.statreg = false
              this.statlog = true
            }
          },
          signout(){
            console.log('siniiii')
            localStorage.removeItem('todo-token')
            window.location.reload(true);
          }
        }
    }
</script>

<style scoped>
.slide-in-elliptic-top-fwd {
	-webkit-animation: slide-in-elliptic-top-fwd 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-elliptic-top-fwd 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2018-5-16 10:50:49
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-elliptic-top-fwd
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-elliptic-top-fwd {
  0% {
    -webkit-transform: translateY(-600px) rotateX(-30deg) scale(0);
            transform: translateY(-600px) rotateX(-30deg) scale(0);
    -webkit-transform-origin: 50% 100%;
            transform-origin: 50% 100%;
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotateX(0) scale(1);
            transform: translateY(0) rotateX(0) scale(1);
    -webkit-transform-origin: 50% 1400px;
            transform-origin: 50% 1400px;
    opacity: 1;
  }
}
@keyframes slide-in-elliptic-top-fwd {
  0% {
    -webkit-transform: translateY(-600px) rotateX(-30deg) scale(0);
            transform: translateY(-600px) rotateX(-30deg) scale(0);
    -webkit-transform-origin: 50% 100%;
            transform-origin: 50% 100%;
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotateX(0) scale(1);
            transform: translateY(0) rotateX(0) scale(1);
    -webkit-transform-origin: 50% 1400px;
            transform-origin: 50% 1400px;
    opacity: 1;
  }
}


div{
  padding-top: 50px;
  padding-left: auto;
  padding-right: auto;
}
h4{
  padding-left: 800px;
}
h4:hover{
  cursor: pointer;
  color: blue
}
h2:hover{
  cursor: pointer;
  color: blue
}
</style>